2025-05-26T21:32:30.102 INFO Instantiating serial manager
2025-05-26T21:32:30.105 INFO TTS160 device initialized successfully
2025-05-26T21:32:30.148 INFO ==STARTUP== Serving on :5555. Time stamps are UTC.
2025-05-26T21:32:36.835 INFO Disc rcv alpacadiscovery1 from ('192.168.8.203', 54558)
2025-05-26T21:32:36.836 INFO Disc rcv alpacadiscovery1 from ('127.0.0.1', 54559)
2025-05-26T21:32:36.843 INFO 192.168.8.203 <- [1]
2025-05-26T21:32:36.844 INFO 127.0.0.1 <- [1]
2025-05-26T21:32:36.845 INFO 192.168.8.203 <- {'ServerName': 'Alpaca TTS160 Server ', 'Manufacturer': 'Reid Smythe', 'Version': '0.1', 'Location': 'Anywhere on Earth'}
2025-05-26T21:32:36.847 INFO 127.0.0.1 <- {'ServerName': 'Alpaca TTS160 Server ', 'Manufacturer': 'Reid Smythe', 'Version': '0.1', 'Location': 'Anywhere on Earth'}
2025-05-26T21:32:36.849 INFO 192.168.8.203 <- [{'DeviceName': 'TTS-160', 'DeviceType': 'Telescope', 'DeviceNumber': 0, 'UniqueID': '1be85f47-5e5b-4993-8593-1678feb2c551'}]
2025-05-26T21:32:36.850 INFO 127.0.0.1 <- [{'DeviceName': 'TTS-160', 'DeviceType': 'Telescope', 'DeviceNumber': 0, 'UniqueID': '1be85f47-5e5b-4993-8593-1678feb2c551'}]
2025-05-26T21:32:40.766 INFO 192.168.8.203 -> PUT /api/v1/telescope/0/connected
2025-05-26T21:32:40.766 INFO 192.168.8.203 -> {'Connected': 'True', 'ClientID': '24566', 'ClientTransactionID': '571'}
2025-05-26T21:32:40.772 INFO Serial connection opened on COM5
2025-05-26T21:32:40.774 INFO Serial connection count: 1
2025-05-26T21:32:40.829 INFO Connected to: TTS-160 Panther
2025-05-26T21:32:40.831 INFO Firmware: 356C (Aug 21 2024)
2025-05-26T21:32:40.906 INFO Site coordinates: 21.347222°, -157.903333°, 0.0m
2025-05-26T21:32:41.509 INFO TTS160 connected successfully
2025-05-26T21:32:41.512 INFO 192.168.8.203 -> GET /api/v1/telescope/0/connected?ClientID=24566&ClientTransactionID=572
2025-05-26T21:32:41.513 INFO 192.168.8.203 <- True
2025-05-26T21:32:41.516 INFO 192.168.8.203 -> GET /api/v1/telescope/0/interfaceversion?ClientID=24566&ClientTransactionID=573
2025-05-26T21:32:41.516 INFO 192.168.8.203 <- 4
2025-05-26T21:32:41.517 INFO 192.168.8.203 -> GET /api/v1/telescope/0/equatorialsystem?ClientID=24566&ClientTransactionID=574
2025-05-26T21:32:41.518 INFO Querying current epoch
2025-05-26T21:32:41.525 INFO Retrieved False, indicating Topocentric Equatorial
2025-05-26T21:32:41.526 INFO 192.168.8.203 <- 1
2025-05-26T21:32:41.528 INFO 192.168.8.203 -> GET /api/v1/telescope/0/trackingrates?ClientID=24566&ClientTransactionID=575
2025-05-26T21:32:41.528 INFO 192.168.8.203 <- [<DriveRates.driveSidereal: 0>, <DriveRates.driveLunar: 1>, <DriveRates.driveSolar: 2>]
2025-05-26T21:32:41.530 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetrightascensionrate?ClientID=24566&ClientTransactionID=576
2025-05-26T21:32:41.530 INFO 192.168.8.203 <- False
2025-05-26T21:32:41.531 INFO 192.168.8.203 -> GET /api/v1/telescope/0/utcdate?ClientID=24566&ClientTransactionID=577
2025-05-26T21:32:41.610 INFO Retrieved date: 2025-05-26 21:32:40+00:00
2025-05-26T21:32:41.613 INFO 192.168.8.203 <- 2025-05-26 21:32:40+00:00
2025-05-26T21:32:41.620 ERROR DriverException: Telescope.Utcdate failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1918, in on_get
    resp.text = PropertyResponse(val, req).json
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in json
    return json.dumps(self, default=lambda o: o.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in <lambda>
    return json.dumps(self, default=lambda o: o.__dict__)
                                              ^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

2025-05-26T21:32:41.625 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sitelatitude?ClientID=24566&ClientTransactionID=578
2025-05-26T21:32:41.627 INFO 192.168.8.203 <- 21.347222222222218
2025-05-26T21:32:41.629 INFO 192.168.8.203 -> GET /api/v1/telescope/0/description?ClientID=24566&ClientTransactionID=579
2025-05-26T21:32:41.630 INFO 192.168.8.203 <- TTS160 Alpaca Driver
2025-05-26T21:32:41.630 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sitelongitude?ClientID=24566&ClientTransactionID=580
2025-05-26T21:32:41.631 INFO 192.168.8.203 <- -157.90333333333336
2025-05-26T21:32:41.637 INFO 192.168.8.203 -> GET /api/v1/telescope/0/siteelevation?ClientID=24566&ClientTransactionID=581
2025-05-26T21:32:41.639 INFO 192.168.8.203 <- 0.0
2025-05-26T21:32:41.641 INFO 192.168.8.203 -> GET /api/v1/telescope/0/altitude?ClientID=24566&ClientTransactionID=582
2025-05-26T21:32:41.658 INFO 192.168.8.203 <- 0.0
2025-05-26T21:32:41.659 INFO 192.168.8.203 -> GET /api/v1/telescope/0/driverinfo?ClientID=24566&ClientTransactionID=583
2025-05-26T21:32:41.659 INFO 192.168.8.203 <- Alpaca telescope
Implements ITelescope
ASCOM Initiative
2025-05-26T21:32:41.660 INFO 192.168.8.203 -> GET /api/v1/telescope/0/atpark?ClientID=24566&ClientTransactionID=584
2025-05-26T21:32:41.660 INFO 192.168.8.203 <- False
2025-05-26T21:32:41.662 INFO 192.168.8.203 -> GET /api/v1/telescope/0/athome?ClientID=24566&ClientTransactionID=585
2025-05-26T21:32:41.662 INFO 192.168.8.203 <- False
2025-05-26T21:32:41.664 INFO 192.168.8.203 -> GET /api/v1/telescope/0/azimuth?ClientID=24566&ClientTransactionID=587
2025-05-26T21:32:41.681 INFO 192.168.8.203 <- 179.9998479605043
2025-05-26T21:32:41.684 INFO 192.168.8.203 -> GET /api/v1/telescope/0/driverversion?ClientID=24566&ClientTransactionID=586
2025-05-26T21:32:41.684 INFO 192.168.8.203 <- 356.0.0
2025-05-26T21:32:41.686 INFO 192.168.8.203 -> GET /api/v1/telescope/0/rightascension?ClientID=24566&ClientTransactionID=588
2025-05-26T21:32:41.702 INFO 192.168.8.203 <- 3.3306418602818173
2025-05-26T21:32:41.706 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canslew?ClientID=24566&ClientTransactionID=589
2025-05-26T21:32:41.707 INFO 192.168.8.203 <- True
2025-05-26T21:32:41.709 INFO 192.168.8.203 -> GET /api/v1/telescope/0/declination?ClientID=24566&ClientTransactionID=590
2025-05-26T21:32:41.726 INFO 192.168.8.203 <- -68.6529489281655
2025-05-26T21:32:41.728 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=591&Axis=0
2025-05-26T21:32:41.730 INFO 192.168.8.203 <- True
2025-05-26T21:32:41.731 INFO 192.168.8.203 -> GET /api/v1/telescope/0/tracking?ClientID=24566&ClientTransactionID=592
2025-05-26T21:32:41.742 INFO 192.168.8.203 <- False
2025-05-26T21:32:41.746 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=593&Axis=0
2025-05-26T21:32:41.747 INFO 192.168.8.203 <- True
2025-05-26T21:32:41.748 INFO 192.168.8.203 -> GET /api/v1/telescope/0/siderealtime?ClientID=24566&ClientTransactionID=594
2025-05-26T21:32:41.768 INFO 192.168.8.203 <- 3.330888888888886
2025-05-26T21:32:41.770 INFO 192.168.8.203 -> GET /api/v1/telescope/0/axisrates?ClientID=24566&ClientTransactionID=595&Axis=0
2025-05-26T21:32:41.770 INFO Calling for axis rate with argument 0
2025-05-26T21:32:41.770 INFO 192.168.8.203 <- [Rate(0.0, 3.5)]
2025-05-26T21:32:41.773 INFO 192.168.8.203 -> GET /api/v1/telescope/0/siteelevation?ClientID=24566&ClientTransactionID=596
2025-05-26T21:32:41.774 INFO 192.168.8.203 <- 0.0
2025-05-26T21:32:41.776 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sitelatitude?ClientID=24566&ClientTransactionID=597
2025-05-26T21:32:41.779 INFO 192.168.8.203 <- 21.347222222222218
2025-05-26T21:32:41.781 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=598&Axis=1
2025-05-26T21:32:41.782 INFO 192.168.8.203 <- True
2025-05-26T21:32:41.783 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sitelongitude?ClientID=24566&ClientTransactionID=599
2025-05-26T21:32:41.784 INFO 192.168.8.203 <- -157.90333333333336
2025-05-26T21:32:41.786 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sideofpier?ClientID=24566&ClientTransactionID=600
2025-05-26T21:32:41.803 ERROR DriverException: Telescope.Sideofpier failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1229, in on_get
    val = TTS160_dev.SideOfPier ## GET PROPERTY ##
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 640, in SideOfPier
    return self._calculate_side_of_pier(self.RightAscension)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 633, in _calculate_side_of_pier
    hour_angle = self.condition_ha(self.SiderealTime - right_ascension)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'TTS160Device' object has no attribute 'condition_ha'

2025-05-26T21:32:41.879 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=601&Axis=1
2025-05-26T21:32:41.880 INFO 192.168.8.203 <- True
2025-05-26T21:32:41.888 INFO 192.168.8.203 -> GET /api/v1/telescope/0/axisrates?ClientID=24566&ClientTransactionID=602&Axis=1
2025-05-26T21:32:41.890 INFO Calling for axis rate with argument 1
2025-05-26T21:32:41.890 INFO 192.168.8.203 <- [Rate(0.0, 3.5)]
2025-05-26T21:32:41.897 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=603&Axis=0
2025-05-26T21:32:41.897 INFO 192.168.8.203 <- True
2025-05-26T21:32:41.900 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=604&Axis=1
2025-05-26T21:32:41.901 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.008 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sideofpier?ClientID=24566&ClientTransactionID=605
2025-05-26T21:32:42.025 ERROR DriverException: Telescope.Sideofpier failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1229, in on_get
    val = TTS160_dev.SideOfPier ## GET PROPERTY ##
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 640, in SideOfPier
    return self._calculate_side_of_pier(self.RightAscension)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 633, in _calculate_side_of_pier
    hour_angle = self.condition_ha(self.SiderealTime - right_ascension)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'TTS160Device' object has no attribute 'condition_ha'

2025-05-26T21:32:42.231 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sideofpier?ClientID=24566&ClientTransactionID=606
2025-05-26T21:32:42.250 ERROR DriverException: Telescope.Sideofpier failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1229, in on_get
    val = TTS160_dev.SideOfPier ## GET PROPERTY ##
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 640, in SideOfPier
    return self._calculate_side_of_pier(self.RightAscension)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 633, in _calculate_side_of_pier
    hour_angle = self.condition_ha(self.SiderealTime - right_ascension)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'TTS160Device' object has no attribute 'condition_ha'

2025-05-26T21:32:42.253 INFO 192.168.8.203 -> GET /api/v1/telescope/0/tracking?ClientID=24566&ClientTransactionID=607
2025-05-26T21:32:42.265 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.269 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetdeclinationrate?ClientID=24566&ClientTransactionID=608
2025-05-26T21:32:42.269 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.272 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetrightascensionrate?ClientID=24566&ClientTransactionID=609
2025-05-26T21:32:42.273 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.276 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansettracking?ClientID=24566&ClientTransactionID=610
2025-05-26T21:32:42.276 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.279 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canfindhome?ClientID=24566&ClientTransactionID=611
2025-05-26T21:32:42.279 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.282 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canpark?ClientID=24566&ClientTransactionID=612
2025-05-26T21:32:42.282 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.284 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetpark?ClientID=24566&ClientTransactionID=613
2025-05-26T21:32:42.284 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.286 INFO 192.168.8.203 -> GET /api/v1/telescope/0/slewing?ClientID=24566&ClientTransactionID=614
2025-05-26T21:32:42.293 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.295 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetguiderates?ClientID=24566&ClientTransactionID=615
2025-05-26T21:32:42.296 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.298 INFO 192.168.8.203 -> GET /api/v1/telescope/0/guideraterightascension?ClientID=24566&ClientTransactionID=616
2025-05-26T21:32:42.308 INFO 192.168.8.203 <- 0.001388888888888889
2025-05-26T21:32:42.313 INFO 192.168.8.203 -> GET /api/v1/telescope/0/guideratedeclination?ClientID=24566&ClientTransactionID=617
2025-05-26T21:32:42.324 INFO 192.168.8.203 <- 0.001388888888888889
2025-05-26T21:32:42.328 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=618&Axis=0
2025-05-26T21:32:42.329 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.331 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canmoveaxis?ClientID=24566&ClientTransactionID=619&Axis=1
2025-05-26T21:32:42.332 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.334 INFO 192.168.8.203 -> GET /api/v1/telescope/0/axisrates?ClientID=24566&ClientTransactionID=620&Axis=0
2025-05-26T21:32:42.335 INFO Calling for axis rate with argument 0
2025-05-26T21:32:42.335 INFO 192.168.8.203 <- [Rate(0.0, 3.5)]
2025-05-26T21:32:42.336 INFO 192.168.8.203 -> GET /api/v1/telescope/0/axisrates?ClientID=24566&ClientTransactionID=621&Axis=1
2025-05-26T21:32:42.336 INFO Calling for axis rate with argument 1
2025-05-26T21:32:42.337 INFO 192.168.8.203 <- [Rate(0.0, 3.5)]
2025-05-26T21:32:42.340 INFO 192.168.8.203 -> GET /api/v1/telescope/0/supportedactions?ClientID=24566&ClientTransactionID=622
2025-05-26T21:32:42.340 INFO 192.168.8.203 <- []
2025-05-26T21:32:42.342 INFO 192.168.8.203 -> GET /api/v1/telescope/0/alignmentmode?ClientID=24566&ClientTransactionID=623
2025-05-26T21:32:42.342 INFO 192.168.8.203 <- 0
2025-05-26T21:32:42.343 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canpulseguide?ClientID=24566&ClientTransactionID=624
2025-05-26T21:32:42.344 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.344 INFO 192.168.8.203 -> GET /api/v1/telescope/0/ispulseguiding?ClientID=24566&ClientTransactionID=625
2025-05-26T21:32:42.346 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.346 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetpierside?ClientID=24566&ClientTransactionID=626
2025-05-26T21:32:42.347 INFO 192.168.8.203 <- False
2025-05-26T21:32:42.348 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canslew?ClientID=24566&ClientTransactionID=627
2025-05-26T21:32:42.348 INFO 192.168.8.203 <- True
2025-05-26T21:32:42.348 INFO 192.168.8.203 -> GET /api/v1/telescope/0/utcdate?ClientID=24566&ClientTransactionID=628
2025-05-26T21:32:42.390 INFO Retrieved date: 2025-05-26 21:32:40+00:00
2025-05-26T21:32:42.393 INFO 192.168.8.203 <- 2025-05-26 21:32:40+00:00
2025-05-26T21:32:42.395 ERROR DriverException: Telescope.Utcdate failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1918, in on_get
    resp.text = PropertyResponse(val, req).json
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in json
    return json.dumps(self, default=lambda o: o.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in <lambda>
    return json.dumps(self, default=lambda o: o.__dict__)
                                              ^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

2025-05-26T21:32:42.601 INFO 192.168.8.203 -> GET /api/v1/telescope/0/utcdate?ClientID=24566&ClientTransactionID=629
2025-05-26T21:32:42.678 INFO Retrieved date: 2025-05-26 21:32:40+00:00
2025-05-26T21:32:42.680 INFO 192.168.8.203 <- 2025-05-26 21:32:40+00:00
2025-05-26T21:32:42.683 ERROR DriverException: Telescope.Utcdate failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1918, in on_get
    resp.text = PropertyResponse(val, req).json
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in json
    return json.dumps(self, default=lambda o: o.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in <lambda>
    return json.dumps(self, default=lambda o: o.__dict__)
                                              ^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

2025-05-26T21:32:42.888 INFO 192.168.8.203 -> GET /api/v1/telescope/0/utcdate?ClientID=24566&ClientTransactionID=630
2025-05-26T21:32:42.930 INFO Retrieved date: 2025-05-26 21:32:41+00:00
2025-05-26T21:32:42.932 INFO 192.168.8.203 <- 2025-05-26 21:32:41+00:00
2025-05-26T21:32:42.933 ERROR DriverException: Telescope.Utcdate failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1918, in on_get
    resp.text = PropertyResponse(val, req).json
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in json
    return json.dumps(self, default=lambda o: o.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in <lambda>
    return json.dumps(self, default=lambda o: o.__dict__)
                                              ^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

2025-05-26T21:32:42.938 INFO 192.168.8.203 -> GET /api/v1/telescope/0/driverversion?ClientID=24566&ClientTransactionID=631
2025-05-26T21:32:42.938 INFO 192.168.8.203 <- 356.0.0
2025-05-26T21:32:44.944 INFO 192.168.8.203 -> GET /api/v1/telescope/0/connected?ClientID=24566&ClientTransactionID=632
2025-05-26T21:32:44.944 INFO 192.168.8.203 <- True
2025-05-26T21:32:44.946 INFO 192.168.8.203 -> GET /api/v1/telescope/0/atpark?ClientID=24566&ClientTransactionID=633
2025-05-26T21:32:44.946 INFO 192.168.8.203 <- False
2025-05-26T21:32:44.946 INFO 192.168.8.203 -> GET /api/v1/telescope/0/athome?ClientID=24566&ClientTransactionID=634
2025-05-26T21:32:44.946 INFO 192.168.8.203 <- False
2025-05-26T21:32:44.946 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansettracking?ClientID=24566&ClientTransactionID=635
2025-05-26T21:32:44.946 INFO 192.168.8.203 <- True
2025-05-26T21:32:44.946 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetdeclinationrate?ClientID=24566&ClientTransactionID=636
2025-05-26T21:32:44.946 INFO 192.168.8.203 <- False
2025-05-26T21:32:44.956 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetrightascensionrate?ClientID=24566&ClientTransactionID=637
2025-05-26T21:32:44.956 INFO 192.168.8.203 <- False
2025-05-26T21:32:44.958 INFO 192.168.8.203 -> GET /api/v1/telescope/0/tracking?ClientID=24566&ClientTransactionID=638
2025-05-26T21:32:44.962 INFO 192.168.8.203 <- False
2025-05-26T21:32:44.962 INFO 192.168.8.203 -> GET /api/v1/telescope/0/altitude?ClientID=24566&ClientTransactionID=639
2025-05-26T21:32:45.023 INFO 192.168.8.203 <- 0.0
2025-05-26T21:32:45.026 INFO 192.168.8.203 -> GET /api/v1/telescope/0/azimuth?ClientID=24566&ClientTransactionID=640
2025-05-26T21:32:45.043 INFO 192.168.8.203 <- 179.9998479605043
2025-05-26T21:32:45.048 INFO 192.168.8.203 -> GET /api/v1/telescope/0/declination?ClientID=24566&ClientTransactionID=641
2025-05-26T21:32:45.066 INFO 192.168.8.203 <- -68.6529489281655
2025-05-26T21:32:45.069 INFO 192.168.8.203 -> GET /api/v1/telescope/0/rightascension?ClientID=24566&ClientTransactionID=642
2025-05-26T21:32:45.085 INFO 192.168.8.203 <- 3.331596789940369
2025-05-26T21:32:45.088 INFO 192.168.8.203 -> GET /api/v1/telescope/0/siderealtime?ClientID=24566&ClientTransactionID=643
2025-05-26T21:32:45.094 INFO 192.168.8.203 <- 3.331999999999997
2025-05-26T21:32:45.094 INFO 192.168.8.203 -> GET /api/v1/telescope/0/tracking?ClientID=24566&ClientTransactionID=644
2025-05-26T21:32:45.112 INFO 192.168.8.203 <- False
2025-05-26T21:32:45.121 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sitelongitude?ClientID=24566&ClientTransactionID=645
2025-05-26T21:32:45.122 INFO 192.168.8.203 <- -157.90333333333336
2025-05-26T21:32:45.122 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sitelatitude?ClientID=24566&ClientTransactionID=646
2025-05-26T21:32:45.122 INFO 192.168.8.203 <- 21.347222222222218
2025-05-26T21:32:45.129 INFO 192.168.8.203 -> GET /api/v1/telescope/0/siteelevation?ClientID=24566&ClientTransactionID=647
2025-05-26T21:32:45.129 INFO 192.168.8.203 <- 0.0
2025-05-26T21:32:45.129 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sideofpier?ClientID=24566&ClientTransactionID=648
2025-05-26T21:32:45.151 ERROR DriverException: Telescope.Sideofpier failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1229, in on_get
    val = TTS160_dev.SideOfPier ## GET PROPERTY ##
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 640, in SideOfPier
    return self._calculate_side_of_pier(self.RightAscension)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 633, in _calculate_side_of_pier
    hour_angle = self.condition_ha(self.SiderealTime - right_ascension)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'TTS160Device' object has no attribute 'condition_ha'

2025-05-26T21:32:45.359 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sideofpier?ClientID=24566&ClientTransactionID=649
2025-05-26T21:32:45.376 ERROR DriverException: Telescope.Sideofpier failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1229, in on_get
    val = TTS160_dev.SideOfPier ## GET PROPERTY ##
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 640, in SideOfPier
    return self._calculate_side_of_pier(self.RightAscension)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 633, in _calculate_side_of_pier
    hour_angle = self.condition_ha(self.SiderealTime - right_ascension)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'TTS160Device' object has no attribute 'condition_ha'

2025-05-26T21:32:45.589 INFO 192.168.8.203 -> GET /api/v1/telescope/0/sideofpier?ClientID=24566&ClientTransactionID=650
2025-05-26T21:32:45.605 ERROR DriverException: Telescope.Sideofpier failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1229, in on_get
    val = TTS160_dev.SideOfPier ## GET PROPERTY ##
          ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 640, in SideOfPier
    return self._calculate_side_of_pier(self.RightAscension)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\TTS160Device.py", line 633, in _calculate_side_of_pier
    hour_angle = self.condition_ha(self.SiderealTime - right_ascension)
                 ^^^^^^^^^^^^^^^^^
AttributeError: 'TTS160Device' object has no attribute 'condition_ha'

2025-05-26T21:32:45.605 INFO 192.168.8.203 -> GET /api/v1/telescope/0/slewing?ClientID=24566&ClientTransactionID=651
2025-05-26T21:32:45.620 INFO 192.168.8.203 <- False
2025-05-26T21:32:45.622 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetguiderates?ClientID=24566&ClientTransactionID=652
2025-05-26T21:32:45.622 INFO 192.168.8.203 <- True
2025-05-26T21:32:45.622 INFO 192.168.8.203 -> GET /api/v1/telescope/0/guideraterightascension?ClientID=24566&ClientTransactionID=653
2025-05-26T21:32:45.636 INFO 192.168.8.203 <- 0.001388888888888889
2025-05-26T21:32:45.639 INFO 192.168.8.203 -> GET /api/v1/telescope/0/guideratedeclination?ClientID=24566&ClientTransactionID=654
2025-05-26T21:32:45.652 INFO 192.168.8.203 <- 0.001388888888888889
2025-05-26T21:32:45.656 INFO 192.168.8.203 -> GET /api/v1/telescope/0/alignmentmode?ClientID=24566&ClientTransactionID=655
2025-05-26T21:32:45.656 INFO 192.168.8.203 <- 0
2025-05-26T21:32:45.656 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canpulseguide?ClientID=24566&ClientTransactionID=656
2025-05-26T21:32:45.656 INFO 192.168.8.203 <- True
2025-05-26T21:32:45.656 INFO 192.168.8.203 -> GET /api/v1/telescope/0/ispulseguiding?ClientID=24566&ClientTransactionID=657
2025-05-26T21:32:45.656 INFO 192.168.8.203 <- False
2025-05-26T21:32:45.656 INFO 192.168.8.203 -> GET /api/v1/telescope/0/cansetpierside?ClientID=24566&ClientTransactionID=658
2025-05-26T21:32:45.656 INFO 192.168.8.203 <- False
2025-05-26T21:32:45.656 INFO 192.168.8.203 -> GET /api/v1/telescope/0/canslew?ClientID=24566&ClientTransactionID=659
2025-05-26T21:32:45.656 INFO 192.168.8.203 <- True
2025-05-26T21:32:45.668 INFO 192.168.8.203 -> GET /api/v1/telescope/0/utcdate?ClientID=24566&ClientTransactionID=660
2025-05-26T21:32:45.706 INFO Retrieved date: 2025-05-26 21:32:44+00:00
2025-05-26T21:32:45.706 INFO 192.168.8.203 <- 2025-05-26 21:32:44+00:00
2025-05-26T21:32:45.716 ERROR DriverException: Telescope.Utcdate failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1918, in on_get
    resp.text = PropertyResponse(val, req).json
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in json
    return json.dumps(self, default=lambda o: o.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in <lambda>
    return json.dumps(self, default=lambda o: o.__dict__)
                                              ^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

2025-05-26T21:32:45.935 INFO 192.168.8.203 -> GET /api/v1/telescope/0/utcdate?ClientID=24566&ClientTransactionID=661
2025-05-26T21:32:45.965 INFO Retrieved date: 2025-05-26 21:32:44+00:00
2025-05-26T21:32:45.979 INFO 192.168.8.203 <- 2025-05-26 21:32:44+00:00
2025-05-26T21:32:45.981 ERROR DriverException: Telescope.Utcdate failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1918, in on_get
    resp.text = PropertyResponse(val, req).json
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in json
    return json.dumps(self, default=lambda o: o.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in <lambda>
    return json.dumps(self, default=lambda o: o.__dict__)
                                              ^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

2025-05-26T21:32:46.188 INFO 192.168.8.203 -> GET /api/v1/telescope/0/utcdate?ClientID=24566&ClientTransactionID=662
2025-05-26T21:32:46.220 INFO Retrieved date: 2025-05-26 21:32:45+00:00
2025-05-26T21:32:46.220 INFO 192.168.8.203 <- 2025-05-26 21:32:45+00:00
2025-05-26T21:32:46.234 ERROR DriverException: Telescope.Utcdate failed
Traceback (most recent call last):
  File "C:\Users\astronomy\TTS160 Alpyca\telescope.py", line 1918, in on_get
    resp.text = PropertyResponse(val, req).json
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in json
    return json.dumps(self, default=lambda o: o.__dict__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\astronomy\TTS160 Alpyca\shr.py", line 248, in <lambda>
    return json.dumps(self, default=lambda o: o.__dict__)
                                              ^^^^^^^^^^
AttributeError: 'datetime.datetime' object has no attribute '__dict__'

2025-05-26T21:32:46.268 INFO 192.168.8.203 -> PUT /api/v1/telescope/0/connected
2025-05-26T21:32:46.268 INFO 192.168.8.203 -> {'Connected': 'False', 'ClientID': '24566', 'ClientTransactionID': '663'}
2025-05-26T21:32:46.268 INFO Serial connection count: 0
2025-05-26T21:32:46.268 ERROR Disconnect error: 'NoneType' object has no attribute 'is_connected'
